language: ruby
bundler_args: --without development --jobs=3 --retry=3
cache: bundler
rvm:
  - 2.1.0
services:
  - redis-server
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - "psql -c 'create database firehouse_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
