smtp:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: '<username>'
  password: '<password>'
  authentication: 'plain'
  enable_starttls_auto: true

public_host: 'public.domain.com'

redis:
  host: <%= ENV['REDIS_PORT_6379_TCP_ADDR']  || 'localhost' %>
