development:
  adapter: postgresql
  encoding: unicode
  database: firehouse_development
  pool: 5
  username: firehouse
  password: firehouse
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: firehouse_test
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'firehouse' %>
  password: <%= ENV['TRAVIS'] ? '' : 'firehouse' %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: firehouse_production
  pool: 5
  username: firehouse
  password: firehouse
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>
